#!/usr/bin/env python3
import os
import subprocess
import sys
import shutil

def main():
    # Determine the directory where this script is located
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Path to Cargo.toml
    cargo_toml = os.path.join(script_dir, "Cargo.toml")
    
    print("=== Libinput Scroll Shim Configurator ===", flush=True)

    # Check if we need to build
    print("Prüfe und baue LD_PRELOAD-shim...", flush=True)
    
    # Check if cargo is installed
    if not shutil.which("cargo"):
        print("Fehler: 'cargo' wurde nicht gefunden. Bitte installiere Rust/Cargo.", flush=True)
        sys.exit(1)

    try:
        subprocess.check_call(["cargo", "build", "--release", "--quiet"], cwd=script_dir)
    except subprocess.CalledProcessError:
        print("Fehler beim Bauen des Rust-Projekts.", flush=True)
        sys.exit(1)

    # Path to the compiled shared library
    lib_path = os.path.join(script_dir, "target", "release", "liblibinput_scroll_shim.so")
    
    if not os.path.exists(lib_path):
        print(f"Fehler: Die Bibliothek wurde nicht unter {lib_path} gefunden.", flush=True)
        sys.exit(1)

    print(f"Shim bereit: {lib_path}", flush=True)
    print("-" * 40, flush=True)

    # Ask for Y speed
    y_speed_str = "1.0"
    while True:
        try:
            val = input("Wie viel Y Geschwindigkeit weißt du? (z.B. 1.0 = normal, 0.5 = langsamer, 2.0 = schneller, -1.0 = invertiert): ").strip()
            if not val:
                val = "1.0"
            
            # Validate input
            float(val)
            y_speed_str = val
            break
        except ValueError:
            print("Bitte eine gültige Zahl eingeben.", flush=True)

    print("-" * 40, flush=True)
    print("Möchtest du das Skript global installieren oder nur testen?", flush=True)
    print("1) Nur testen (startet ein Programm jetzt)")
    print("2) GLOBAL installieren (für den ganzen Desktop, erfordert Ab/Anmelden)")
    
    choice = input("Wahl (1/2): ").strip()

    if choice == "2":
        # Global Install
        config_dir = os.path.expanduser("~/.config/environment.d")
        os.makedirs(config_dir, exist_ok=True)
        conf_file = os.path.join(config_dir, "99-libinput-scroll-shim.conf")
        
        try:
            with open(conf_file, "w") as f:
                f.write(f"# Generated by libinput-scroll-shim\n")
                f.write(f"SCROLL_SCALE_Y={y_speed_str}\n")
                f.write(f"LD_PRELOAD={lib_path}\n")
            
            print(f"\n[ERFOLG] Konfiguration geschrieben nach: {conf_file}", flush=True)
            print("Bitte melde dich jetzt ab und wieder an (Logout/Login), damit die Änderungen wirksam werden.", flush=True)
            print("Falls danach Probleme auftreten (z.B. Login geht nicht), lösche die Datei über ein TTY mit:", flush=True)
            print(f"rm {conf_file}", flush=True)
            
        except Exception as e:
            print(f"Fehler beim Schreiben der Konfiguration: {e}", flush=True)
            sys.exit(1)
            
    else:
        # Run Once (Test)
        prog_input = input("Welches Programm möchtest du testen? (Leer lassen für 'gnome-terminal'): ").strip()
        
        cmd = []
        if prog_input:
            import shlex
            cmd = shlex.split(prog_input)
        else:
            cmd = ["gnome-terminal"]
            print("Kein Programm angegeben. Starte gnome-terminal...", flush=True)

        env = os.environ.copy()
        env["LD_PRELOAD"] = lib_path
        env["SCROLL_SCALE_Y"] = y_speed_str
        
        print(f"Starte: {' '.join(cmd)} mit SCROLL_SCALE_Y={y_speed_str}", flush=True)
        
        try:
            os.execvpe(cmd[0], cmd, env)
        except FileNotFoundError:
            print(f"Fehler: Das Programm '{cmd[0]}' wurde nicht gefunden.", flush=True)
            sys.exit(1)
        except Exception as e:
            print(f"Fehler beim Starten: {e}", flush=True)
            sys.exit(1)

if __name__ == "__main__":
    main()
